spring:
  application:
    name: tgr-eureka-fegin-client

server:
  port: 8767

eureka: 
  client: 
    serviceUrl: 
      defaultZone:  http://localhost:8761/eureka/
      
######   Hystrix熔断器
feign:
  hystrix:  
    enabled: true #开启Hystrix熔断器

######   Hystrix熔断器结束

