spring.profiles.active:

#java -jar -Dspring.profiles.active=b tgr_cloud_client-1.0-SNAPSHOT.jar
#java -jar -Dspring.profiles.active=a tgr_cloud_client-1.0-SNAPSHOT.jar

#java.lang.IllegalStateException: Request URI does not contain a valid hostname: http://tgr_cloud_client/hi?name=forezp
#使用ribbon实现负载均衡的时候，服务名称不能用下划线，换成中划线。
    
  # defaultZone 为默认的 Zone，来源于 AWS 的概念 。区域（ Region ）和可
  #用区（ Avai lability Zone, AZ ）是 AWS 的另外两个概念。区域是指服务器所在的区域，比如北
  #美洲、南美洲、欧洲和亚洲等，每个区域一般由多个可用区组成 。 在本案例中 defaultZone 是
  #指 Eureka Server 的注册地址 。
  
  #启动打印如下内容 说明client已向server注册
  #[           main] t.TgrCloudClientApplication              : Started TgrCloudClientApplication in 4.188 seconds (JVM running for 4.898)
  #[nfoReplicator-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_TGR_CLOUD_CLIENT/DESKTOP-BV9KA48:tgr_cloud_client:8762 - registration status: 204
  

#eureka结束